config/routes.rb
Rails.application.routes.draw do
  resources :datasets
  get 'welcome/index'

  resources :nodes
  root 'welcome#index'

end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
end

app/models/node.rb
class Node < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  before_action :set_dataset, only: [:show, :edit, :update, :destroy]

  # GET /datasets
  # GET /datasets.json
  def index
    @datasets = Dataset.all
  end

  # GET /datasets/1
  # GET /datasets/1.json
  def show
  end

  # GET /datasets/new
  def new
    @dataset = Dataset.new
  end

  # GET /datasets/1/edit
  def edit
  end

  # POST /datasets
  # POST /datasets.json
  def create
    @dataset = Dataset.new(dataset_params)

    respond_to do |format|
      if @dataset.save
        format.html { redirect_to @dataset, notice: 'Dataset was successfully created.' }
        format.json { render :show, status: :created, location: @dataset }
      else
        format.html { render :new }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datasets/1
  # PATCH/PUT /datasets/1.json
  def update
    respond_to do |format|
      if @dataset.update(dataset_params)
        format.html { redirect_to @dataset, notice: 'Dataset was successfully updated.' }
        format.json { render :show, status: :ok, location: @dataset }
      else
        format.html { render :edit }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datasets/1
  # DELETE /datasets/1.json
  def destroy
    @dataset.destroy
    respond_to do |format|
      format.html { redirect_to datasets_url, notice: 'Dataset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dataset
      @dataset = Dataset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dataset_params
      params.require(:dataset).permit(:start_time, :end_time, :address, :name, :author)
    end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:address, :description, :design, :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/datasets/_form.html.erb
<%= form_for(@dataset) do |f| %>
  <% if @dataset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dataset.errors.count, "error") %> prohibited this dataset from being saved:</h2>

      <ul>
      <% @dataset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.number_field :address %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/datasets/edit.html.erb
<h1>Editing Dataset</h1>

<%= render 'form' %>

<%= link_to 'Show', @dataset %> |
<%= link_to 'Back', datasets_path %>

app/views/datasets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Datasets</h1>

<p>Datasets are specific windows of data that you can query. Useful
if you're running tests or if you want to show off a particular
set of data.
</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @datasets.each do |dataset| %>
      <tr>
        <td><%= link_to dataset.name , dataset %></td>
        <td><%= dataset.address %></td>
        <td><%= dataset.author %></td>
        <td><%= link_to 'Edit', edit_dataset_path(dataset) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dataset', new_dataset_path %>

app/views/datasets/new.html.erb
<h1>New Dataset</h1>

<%= render 'form' %>

<%= link_to 'Back', datasets_path %>

app/views/datasets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @dataset.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @dataset.end_time %>
</p>

<p>
  <strong>Address:</strong>
  <%= @dataset.address %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dataset.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @dataset.author %>
</p>

<div class="nodeGraph" id="node-graph"
        data-start_time="<%= @dataset.start_time %>"
        data-end_time="<%= @dataset.end_time %>"
        data-nodeAddress="<%= @dataset.address %>" style="height:300px; width:500px"></div>

<%= link_to 'Edit', edit_dataset_path(@dataset) %> |
<%= link_to 'Back', datasets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WdacManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/canvasjs/1.7.0/canvasjs.min.js"></script>
</head>
<body data-no-turbolink>
    <p>
    <span> <strong> Links: </strong></span>
    <span> <%= link_to('Home', controller: 'welcome') %> </span>
    <span> <%= link_to('Data Nodes', controller: 'nodes') %> </span>
    <span> <%= link_to('Datasets', controller: 'datasets') %> </span>
    </p>
    <hr />
<%= yield %>

</body>
</html>

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.number_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :design %><br>
    <%= f.text_field :design %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing Node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registered Data Nodes</h1>
<p> This pages lists all currently registered data nodes in the SCEL network. </p>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Design</th>
      <th>Description</th>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= link_to node.address, node %></td>
        <td><%= node.design %></td>
        <td><%= node.description %></td>
        <td><%= node.name %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <!-- <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New Node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Address:</strong>
  <%= @node.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @node.description %>
</p>

<p>
  <strong>Design:</strong>
  <%= @node.design %>
</p>

<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>

<h3>Battery Voltage</h3>
<div class="nodeGraph" id="node-graph" data-nodeAddress="<%=@node.address%>" style="height:300px; width:500px"></div>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>

app/views/welcome/index.html.erb
<h1>SCEL Data Network</h1>
<p>Pretty plain. Check out data nodes to see the network. </p>


<hr />
<h2>Current Status</h2>

<h3>Battery Voltage for Dragonfruit Test</h3>
<div class="nodeGraph" id="dragonfruit-graph" data-nodeAddress="888" style="height:300px; width:700px"></div>

<h3>Battery Voltage for Cranberry Test</h3>
<div class="nodeGraph" id="cranberry-graph" data-nodeAddress="889" style="height:300px; width:700px"></div>